# Generated by Django 3.2.9 on 2021-12-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=1, upload_to='Users/', verbose_name='image'),
            preserve_default=False,
        ),
    ]
