# Generated by Django 3.2.9 on 2021-12-30 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
