# Generated by Django 3.2.9 on 2021-12-30 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_delete_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertising',
            name='center',
        ),
    ]
