# Generated by Django 3.2.9 on 2021-12-30 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_remove_advertising_center'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertising',
            old_name='name',
            new_name='title',
        ),
    ]
