# Generated by Django 3.2.9 on 2021-12-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_rename_name_advertising_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
    ]
