# Generated by Django 3.2.9 on 2022-01-14 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='time',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='title',
        ),
    ]
