# Generated by Django 3.2.9 on 2021-12-22 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0060_centeropinion_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centeropinion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='serviceopinion',
            name='user',
        ),
    ]
