# Generated by Django 3.2.9 on 2021-12-23 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0062_auto_20211223_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='center',
        ),
    ]
