# Generated by Django 3.2.9 on 2021-12-23 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0063_remove_service_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centeropinion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='serviceopinion',
            name='user',
        ),
        migrations.AddField(
            model_name='service',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='commerce.center'),
        ),
    ]
