# Generated by Django 3.2.9 on 2021-12-23 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerce', '0064_auto_20211223_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='centeropinion',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CenterOpinions', to='account.user', verbose_name='user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceopinion',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ServiceOpinions', to='account.user', verbose_name='user'),
            preserve_default=False,
        ),
    ]
