# Generated by Django 3.2.9 on 2021-12-25 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0066_auto_20211223_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='advertisings', to='commerce.center'),
            preserve_default=False,
        ),
    ]
