# Generated by Django 3.2.9 on 2021-12-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0067_advertising_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center_image',
            name='image',
            field=models.ImageField(upload_to='center/', verbose_name='image'),
        ),
    ]
