# Generated by Django 3.2.9 on 2021-12-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0068_alter_center_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center_image',
            name='image',
            field=models.ImageField(upload_to='centers/', verbose_name='image'),
        ),
    ]
