# Generated by Django 3.2.9 on 2021-12-25 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0069_alter_center_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_image',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Service_images', to='commerce.service', verbose_name='service'),
        ),
    ]
