# Generated by Django 3.2.9 on 2021-12-25 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0070_alter_service_image_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center_image',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Center_images', to='commerce.center', verbose_name='center'),
        ),
        migrations.AlterField(
            model_name='center_image',
            name='image',
            field=models.ImageField(upload_to='center/', verbose_name='image'),
        ),
    ]
