# Generated by Django 3.2.9 on 2021-12-25 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0072_auto_20211225_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
    ]
