# Generated by Django 3.2.9 on 2021-12-25 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0076_reservation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='commerce.service'),
            preserve_default=False,
        ),
    ]
