# Generated by Django 3.2.9 on 2021-12-25 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0077_reservation_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centeropinion',
            name='time',
        ),
        migrations.RemoveField(
            model_name='serviceopinion',
            name='time',
        ),
    ]
