# Generated by Django 3.2.9 on 2021-12-31 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0079_centeropinion_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centeropinion',
            name='rate',
        ),
    ]
