# Generated by Django 3.2.9 on 2021-12-31 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0080_remove_centeropinion_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='title',
        ),
    ]
