# Generated by Django 3.2.9 on 2021-12-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0081_auto_20211231_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='time'),
        ),
    ]
