# Generated by Django 3.2.9 on 2022-01-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0082_reservation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='center',
            name='close_days',
            field=models.TextField(blank=True, null=True, verbose_name='close_days'),
        ),
        migrations.AlterField(
            model_name='center',
            name='open_days',
            field=models.TextField(blank=True, null=True, verbose_name='open_days'),
        ),
    ]
